window.requireConfig = {
	baseUrl: window.requireRoot || './',
	paths: {
		// libraries
		text: 'lib/js/text',
		extend: 'lib/js/extend',
		promise: 'lib/js/promise.min',
		// urushi core objects.
		addInputEventListener: 'urushi/base/addInputEventListener',
		browser: 'urushi/base/browser',
		event: 'urushi/base/event',
		legacy: 'urushi/base/legacy',
		node: 'urushi/base/node',
		parser: 'urushi/base/parser',
		removeInputEventListener: 'urushi/base/removeInputEventListener',
		templateEngine: 'urushi/base/templateEngine',
		Urushi: 'urushi/Urushi',
		util: 'urushi/base/util',
		xhr: 'urushi/base/xhr',
		// urushi classes.
		templateConfig: 'urushi/material/js/templateConfig',
		materialConfig: 'urushi/material/js/materialConfig',
		_Base: 'urushi/material/js/_Base',
		_collectionMixin: 'urushi/material/js/_collectionMixin',
		_CollectionWidgetBase: 'urushi/material/js/_CollectionWidgetBase',
		_CollectionItemBase: 'urushi/material/js/_CollectionItemBase',
		Button: 'urushi/material/js/Button',
		Calendar: 'urushi/material/js/Calendar',
		Checkbox: 'urushi/material/js/Checkbox',
		ContextMenu: 'urushi/material/js/ContextMenu',
		_ContextMenuItem: 'urushi/material/js/_ContextMenuItem',
		Dialog: 'urushi/material/js/Dialog',
		DropDown: 'urushi/material/js/DropDown',
		Hamburger: 'urushi/material/js/Hamburger',
		IconButton: 'urushi/material/js/IconButton',
		Input: 'urushi/material/js/Input',
		Panel: 'urushi/material/js/Panel',
		Radiobox: 'urushi/material/js/Radiobox',
		Ripple: 'urushi/material/js/Ripple',
		Textarea: 'urushi/material/js/Textarea',
		Toast: 'urushi/material/js/Toast',
		ToastManager: 'urushi/material/js/ToastManager',
		ToggleButton: 'urushi/material/js/ToggleButton',
		Tooltip: 'urushi/material/js/Tooltip',
		// urushi module templates.
		buttonTemplate: 'urushi/material/template/button.html',
		calendarTemplate: 'urushi/material/template/calendar.html',
		checkboxTemplate: 'urushi/material/template/checkbox.html',
		contextMenuTemplate: 'urushi/material/template/context-menu.html',
		dialogTemplate: 'urushi/material/template/dialog.html',
		dropDownTemplate: 'urushi/material/template/drop-down.html',
		hamburgerTemplate: 'urushi/material/template/hamburger.html',
		iconButtonTemplate: 'urushi/material/template/icon-button.html',
		inputTemplate: 'urushi/material/template/input.html',
		inputWithCaptionTemplate: 'urushi/material/template/input-with-caption.html',
		panelTemplate: 'urushi/material/template/panel.html',
		radioboxTemplate: 'urushi/material/template/radiobox.html',
		textareaTemplate: 'urushi/material/template/textarea.html',
		textareaWithCaptionTemplate: 'urushi/material/template/textarea-with-caption.html',
		toastTemplate: 'urushi/material/template/toast.html',
		toastManagerTemplate: 'urushi/material/template/toast-manager.html',
		toggleButtonTemplate: 'urushi/material/template/toggle-button.html',
		tooltipTemplate: 'urushi/material/template/tooltip.html',
	},
	// Counterplan for browser cache.
	urlArgs: 'bust=' + (new Date()).getTime()
};
